sudo: false
language: node_js
node_js: 6
env:
  global:
  - secure: GxQwdMcMY9CVX1N1y+hIxsmuuu1fCsRy29ajl2bWUJvhJzXoA9XBxuPgupc9BdQR4BkE6PxFmwpwKzFcBl0reYNaDBCVAf2g/ByCOUdXwpZ+Er0iSfK20bYcEXXBe5D8BJnZIVqCavuUILk424AJvxVjpXZelE9noGVLEPeT6V4=
  - secure: JbIvIggLmYe3yO5TR+Cgpe/eIkGjifPvHIk3JKewkY8Sk/maSDC3CiNB3w5BByt2PHr9gA/d83JbyJ1F19N4tRXaA39RQq6GAb0ljFoujwgf0chY0ELCPkdxbiP7St8i3dqNSWECaQNbhgbzSzOV0U2vfgtv1lmT8yQChrAEnEU=
  - secure: SmQ+YNersmisfZhj1IRFLGdWnSs6Fas9BNl4J6DI4BRbv/EKU07lZqi5D7reDcEo3rinxXES9hksR+/oUC73/OHE9d19TEh0O20uaq9rciLtOrgQAHVfj/k38GtG8ZQE7DpKe/kesSreBagbebMk7AIYG0hf981qebt5qs8B8dI=
  - secure: jNI8ffR36mNGDIF3EFusc2bNYOqpay39WtM9qFnYB996L8vKBSPqvb5Zpdw1h4MNjGPwn25MMjqtFbkWwNjpi2yMoIWMeR4EREzLzrH0W8BAEJ+o9comd1t/hlePnMVfPwKQHhQHzaJWn1DuHoOmXMtGfkeDFS2aw8nEIR7Us8k=
  - secure: ZtOMAl1lJhtad+rNMiZTVEBJCcmNXPG2bOqXqNXYMmae4cVQrqYvA+87O4CbBgxI5DigX/GOTaoiFpvK88JJ1fBowa5etKpJE4KaktXDv/oHFBCfLS6EqyBLh2S60kTOzLC/6sgW0VZVmCauGEhd/GuHmgyE2e0j70x40PmyMrJvVWp4Rw67xw00G0fC0iLa3lkrTgt1malRy9+aK+ZbJ/3su7ic2v9WKJbTri8HHNKJ+kI4/7nGWWQYoo2eh0lyOx1JBe8eHjhCfHhECxEdLB1qQbbAAaa0oOpN23DhEf2zGnN9mIL+1r6U980jfCB27acSw6CUH2jlk0MBSaPElFpoAJ1PGTRSZFMwIHkp5HWOGgPyR7sP/OWAPsO8sIYsjETxhDEBsjwYqfR/pXCLaHU76yXNQscHmbQfw7VlaFcNDvCo40aPmH/SY80iRvaptm3F5bFwvtT7bUzU40jIzF6MaaxW6CdZwitPCFXw5Wp5744qrAgKyEdHnkZtaPpkh0U2roEvx4VJ7iDRkhuW5spLtVreBDjTb2vlGJ8qQSc69eQ40pwRdcvC2vI3TPbDSfnskCE2JeGFYq/2lvWIOPlJE2tXUAdPv64gXoXHB8pHHTeZuz+Conz1D42akDATRqhz+tZM1otBJiRAtzD134Zm9D+VZZxBeeecSrLsn/E=
  - secure: OWayTfT5KypA4XQt/w3zYAvPZqthnv9TDFGj1ZL/1w2m2Ewfh74m00wlubMe2FMddc/WIcmbPRVFoev6hetz4Wslo3m83I+cYusUVknGpbjVGcT6f7dDx4k/eV04x2uS7I6VnvNeRaAQOVs2Yi1wfVpfbC8GTAboXWvEQDI9LLlr0JlC5iqExO1V3sDGRLbaEttsuUyOCuNVftHRDmyuG55zLBePyqFTBZMSNCEKCHoM78iyGaaS2sqina2JjLXnGgmhZmU6XWwMZ1SecCIXew93neJJm5ugE8tGv5/sepe/jGkUjemq5V4SG717Nc06UxxM/FjNnXTN48jQPnrB2PPNe7OkM2bFRL3nQf3JGy+ACi7RDQLkIJnMZQ12toofM9xiUhPopthQXLQuO6TAZLqDYSc0hnF/KhNxa/Gegh5QW0fGdfG+V7AqPxGjCopcK5yCVapbg8MgMHyNfr0iPe/kFsi1DNGFD0oOZ68dHlP8bs078+5IKan1hZ+c0Uzg5kmq1BLkG91FagIrTdVlQ8dYqfT9vCqNjdR7GNKI9MsmSoOuqRfRfeo8xgdOjgbVyy91iCGG3B+OLDt/UzcP2w7P6ubCduaNeCurU37y6mL04ZtlllFEjGRf4GeeD6mviA1Edcn2Bm7wDQCnfQDYPIdpc1vC7tgcmdaFqUTdWJ8=
  - secure: ozBJzvdTR2mKkpG47AQF/+EQOUjh9VYs7HJJkqX+KfXMmkRbHWNl8F00fe/R8SjZK1Az5QzLKxihQTli8j7MPY89upBwgmrYq34UCtHHR9yTPwX52EzkTDBgy2+MNycXBpkjLnIpmx06kw0AYLjw7Qr809n0cUPgcqTgjd/M3bg=
  - secure: NXRxA0b6YTzRG3ReEdWY/0ez+IHJf0glS0kJW9oPfqeuZbVrv248/URw1ZsXD290sBKEoXBPy6dbSVf/ZgbDXIFS1vp4NGnLaBj1Fs6G87spbGb+f26uodLmn0HOdr1CKrcJjtPGqL/U5CuiLChlJuT/FVFgLqq7e1rYw2zexxQ=
cache:
  apt: true
  yarn: true
  directories:
  - .lanyon
install: npm install
script: npm run lint && npm run test
before_cache:
- rm -f ./node_modules/.bin/which
deploy:
  skip_cleanup: true
  provider: script
  script: node_modules/lanyon/scripts/ci-deploy.sh
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux
notifications:
  slack:
    secure: Vx2sPpEgzU3LWCfcfRleeHIVKfhAxC9k0DO3hKSOTv4fjn68yS10AIQUjEpkg5CPmckAikNgKeLjHMdnFZbysjRT/aRqe3/YNnStmWtyFZj+C3hboKQ85POQbDU+D3GFaO0rn3lXMMXB4AOahpkaVnABSXcXlXKDYKfDmn+5Vh8=
